---
# Ansible managed
services:
  qgis-server:
    image: sourcepole/qwc-qgis-server:${QGIS_SERVER_TAG}
    restart: unless-stopped
    cpu_shares: ${QGIS_SERVER_CPU_SHARES}
    ports:
      - "${QGIS_SERVER_IP}:${QGIS_SERVER_PORT}:80"
    environment:
      FCGI_IDLE_TIMEOUT: "${FCGI_IDLE_TIMEOUT}"
      FCGI_IO_TIMEOUT: "${FCGI_IO_TIMEOUT}"
      FCGI_MIN_PROCESSES: "${FCGI_MIN_PROCESSES}"
      FCGI_MAX_PROCESSES: "${FCGI_MAX_PROCESSES}"
      QGIS_SERVER_CACHE_SIZE: "${QGIS_SERVER_CACHE_SIZE}"
      QGIS_SERVER_DISABLE_GETPRINT: "${QGIS_SERVER_DISABLE_GETPRINT}"
      QGIS_SERVER_FORCE_READONLY_LAYERS: "${QGIS_SERVER_FORCE_READONLY_LAYERS}"
      QGIS_SERVER_IGNORE_BAD_LAYERS: "${QGIS_SERVER_IGNORE_BAD_LAYERS}"
      QGIS_SERVER_LOG_LEVEL: "${QGIS_SERVER_LOG_LEVEL}"
      QGIS_SERVER_PARALLEL_RENDERING: "${QGIS_SERVER_PARALLEL_RENDERING}"
      QGIS_SERVER_PROJECT_CACHE_STRATEGY: "${QGIS_SERVER_PROJECT_CACHE_STRATEGY}"
      LOCALE: "${LOCALE}"
      TZ: "${TZ}"
    volumes:
      - ${DATA_DIR}/qgis-server/mapdata:/data:ro
      - ${DATA_DIR}/qgis-server/fonts:/usr/local/share/fonts:ro
    tmpfs:
      - /.cache:mode=777
