---
# Ansible managed
services:
  varnish:
    image: varnish:${VARNISH_TAG}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      VARNISH_SIZE: ${VARNISH_SIZE}
    volumes:
      - ./conf/varnish:/etc/varnish:ro
    tmpfs:
      - /var/lib/varnish/varnishd:exec,mode=777
    networks:
      - default
      - revproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.varnish.rule=Host(`${MAIN_HOST}`) || (Host(`${MAP_HOST_1}`) || Host(`${MAP_HOST_2}`) || Host(`${MAP_HOST_3}`) || Host(`${MAP_HOST_4}`)) && Method(`GET`) && PathPrefix(`/tiles`)"
      - "traefik.http.routers.varnish.tls=true"
      - "traefik.http.routers.varnish.tls.certresolver=letsencrypt"
      - "traefik.http.routers.varnish.middlewares=varnish"
      - "traefik.http.services.varnish.loadbalancer.server.port=80"
      - "traefik.http.middlewares.varnish.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.varnish.headers.custombrowserxssvalue=0"
      - "traefik.http.middlewares.varnish.headers.framedeny=true"
      - "traefik.docker.network=${REVPROXY_NETWORK_NAME}"

networks:
  revproxy:
    external: true
    name: ${REVPROXY_NETWORK_NAME}
