---
# Ansible managed
services:
  traefik:
    image: traefik:${TRAEFIK_TAG}
    restart: always
    command:
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
    environment:
      TZ: ${TZ}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/traefik:/etc/traefik:ro
      - ${DATA_DIR}/traefik/data:/data
      - ${DATA_DIR}/traefik/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
