---
# Ansible managed
services:
  nginx:
    image: nginxinc/nginx-unprivileged:${NGINX_TAG}
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
    ports:
      - "${NGINX_IP}:${NGINX_PORT}:8080"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d:ro
      - ${DATA_DIR}/leaflet/dist:/usr/share/nginx/html:ro
